### ISSUE TITLE
Respond with a HTTP error when trying to request a user ID that doesn't exist

### ISSUE THREAD

**Issue by Nareshp1** [Keith-Khadar/nwktheory#12]
https://github.com/Keith-Khadar/nwktheory/blob/69809bfbff4eb4b5ca91d7b029cb85a996473672/src/server/api/server.go#L41-L51

Edit here to add HTTP response with mux.

**Comment by alexchristy** [comment]
https://github.com/Keith-Khadar/nwktheory/blob/69809bfbff4eb4b5ca91d7b029cb85a996473672/src/server/storage/mongo.go#L45-L62

Check here for mongoDB error when determining whether user exists.
